name: Update Homebrew Formula

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., v0.14.0)'
        required: true
        type: string

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="${{ inputs.version }}"
          fi
          # Remove 'v' prefix if present
          VERSION_CLEAN="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version_clean=${VERSION_CLEAN}" >> $GITHUB_OUTPUT

      - name: Download and verify release assets
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          
          # Download all platform binaries
          mkdir -p assets
          cd assets
          
          wget -O x86_64-macos.tar.gz "https://github.com/hendriknielaender/zvm/releases/download/${VERSION}/x86_64-macos-zvm.tar.gz"
          wget -O aarch64-macos.tar.gz "https://github.com/hendriknielaender/zvm/releases/download/${VERSION}/aarch64-macos-zvm.tar.gz"
          wget -O x86_64-linux.tar.gz "https://github.com/hendriknielaender/zvm/releases/download/${VERSION}/x86_64-linux-zvm.tar.gz"
          wget -O aarch64-linux.tar.gz "https://github.com/hendriknielaender/zvm/releases/download/${VERSION}/aarch64-linux-zvm.tar.gz"
          
          # Compute and store SHA256 checksums
          echo "SHA_X86_64_MACOS=$(sha256sum x86_64-macos.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "SHA_AARCH64_MACOS=$(sha256sum aarch64-macos.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "SHA_X86_64_LINUX=$(sha256sum x86_64-linux.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "SHA_AARCH64_LINUX=$(sha256sum aarch64-linux.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Update formula
        run: |
          VERSION_CLEAN="${{ steps.version.outputs.version_clean }}"
          
          # Update version
          sed -i "s/version \".*\"/version \"${VERSION_CLEAN}\"/" Formula/zvm.rb
          
          # Update SHA256 hashes using more robust sed patterns
          sed -i '/x86_64-macos-zvm.tar.gz/{n;s/sha256 ".*"/sha256 "'"${SHA_X86_64_MACOS}"'"/;}' Formula/zvm.rb
          sed -i '/aarch64-macos-zvm.tar.gz/{n;s/sha256 ".*"/sha256 "'"${SHA_AARCH64_MACOS}"'"/;}' Formula/zvm.rb
          sed -i '/x86_64-linux-zvm.tar.gz/{n;s/sha256 ".*"/sha256 "'"${SHA_X86_64_LINUX}"'"/;}' Formula/zvm.rb
          sed -i '/aarch64-linux-zvm.tar.gz/{n;s/sha256 ".*"/sha256 "'"${SHA_AARCH64_LINUX}"'"/;}' Formula/zvm.rb

      - name: Test formula
        run: |
          # Style check (works with file path)
          brew style Formula/zvm.rb
          
          # Basic syntax check
          ruby -c Formula/zvm.rb
          echo "✅ Formula syntax is valid"

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: bump zvm to ${{ steps.version.outputs.version }}"
          title: "feat: bump zvm to ${{ steps.version.outputs.version }}"
          body: |
            ## 🚀 Version Bump: zvm ${{ steps.version.outputs.version }}
            
            This PR automatically updates the zvm formula to version ${{ steps.version.outputs.version }}.
            
            ### Changes
            - Updated version to `${{ steps.version.outputs.version_clean }}`
            - Updated SHA256 checksums for all platform binaries
            - Verified formula passes `brew audit` and `brew style` checks
            
            ### Verification
            - [ ] Formula syntax is valid
            - [ ] All platform binaries are available
            - [ ] SHA256 checksums match release assets
            
            **Auto-generated by GitHub Actions**
          branch: bump/zvm-${{ steps.version.outputs.version_clean }}
          base: main
          delete-branch: true

  # Test the formula on different platforms
  test-formula:
    needs: update-formula
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: bump/zvm-${{ needs.update-formula.outputs.version_clean }}

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Test formula installation
        run: |
          # Test installation directly from file
          brew install --build-from-source Formula/zvm.rb
          
          # Verify installation
          zvm --version
          zvm list
          
          # Clean up
          brew uninstall zvm
