name: Bump Homebrew Formula

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types: [published]

jobs:
  bump-formula:
    name: Bump Homebrew Formula
    runs-on: ubuntu-latest

    env:
      VERSION: "${{ github.ref_name }}"

    steps:
      - name: Check out the zvm repository
        uses: actions/checkout@v4

      - name: Download artifacts and compute SHAs
        run: |
          wget https://github.com/hendriknielaender/zvm/releases/download/${VERSION}/x86_64-macos-zvm.tar.gz
          wget https://github.com/hendriknielaender/zvm/releases/download/${VERSION}/aarch64-macos-zvm.tar.gz
          wget https://github.com/hendriknielaender/zvm/releases/download/${VERSION}/x86_64-linux-zvm.tar.gz
          wget https://github.com/hendriknielaender/zvm/releases/download/${VERSION}/aarch64-linux-zvm.tar.gz

          # Compute SHAs for each artifact.
          export SHA_X86_64_MACOS=$(sha256sum x86_64-macos-zvm.tar.gz | cut -d ' ' -f1)
          export SHA_AARCH64_MACOS=$(sha256sum aarch64-macos-zvm.tar.gz | cut -d ' ' -f1)
          export SHA_X86_64_LINUX=$(sha256sum x86_64-linux-zvm.tar.gz | cut -d ' ' -f1)
          export SHA_AARCH64_LINUX=$(sha256sum aarch64-linux-zvm.tar.gz | cut -d ' ' -f1)

          echo "SHA_X86_64_MACOS=$SHA_X86_64_MACOS" >> $GITHUB_ENV
          echo "SHA_AARCH64_MACOS=$SHA_AARCH64_MACOS" >> $GITHUB_ENV
          echo "SHA_X86_64_LINUX=$SHA_X86_64_LINUX" >> $GITHUB_ENV
          echo "SHA_AARCH64_LINUX=$SHA_AARCH64_LINUX" >> $GITHUB_ENV

      - name: Update formula file
        working-directory: Formula
        run: |
          # Update the version line
          sed -i.bak "s/^  version .*/  version \"${VERSION}\"/" zvm.rb

          # Update each sha256 entry; adjust sed expressions as needed for your formula format.
          sed -i.bak "s|sha256 \".*\"|sha256 \"${SHA_X86_64_MACOS}\"|g" zvm.rb
          sed -i.bak "s|sha256 \".*\"|sha256 \"${SHA_AARCH64_MACOS}\"|g" zvm.rb
          sed -i.bak "s|sha256 \".*\"|sha256 \"${SHA_X86_64_LINUX}\"|g" zvm.rb
          sed -i.bak "s|sha256 \".*\"|sha256 \"${SHA_AARCH64_LINUX}\"|g" zvm.rb

          rm -f zvm.rb.bak

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bump/zvm-${VERSION}
          commit-message: "chore(homebrew): bump zvm formula to v${VERSION}"
          title: "chore(homebrew): bump zvm formula to v${VERSION}"
          body: |
            This PR bumps the zvm formula to version ${VERSION}.

