name: Test Homebrew Formula

on:
  pull_request:
    paths: ['Formula/**']
  push:
    paths: ['Formula/**']
    branches: [main]

jobs:
  test-formula:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
        formula: [zvm, zvm@0.13]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run Homebrew tests
        run: |
          # Check formula syntax and style (file paths work for style)
          brew style Formula/${{ matrix.formula }}.rb
          
          # Basic syntax check
          ruby -c Formula/${{ matrix.formula }}.rb
          echo "✅ Formula syntax is valid"
          
          # Verify the formula can be installed and works
          brew install --build-from-source Formula/${{ matrix.formula }}.rb
          
          # Test basic functionality
          if [ "${{ matrix.formula }}" = "zvm" ]; then
            zvm --version
            zvm list
          else
            # For versioned formula, test with full path
            "$(brew --prefix ${{ matrix.formula }})/bin/zvm" --version
          fi
          
          # Clean up
          brew uninstall ${{ matrix.formula }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        
      - name: Lint all formulas
        run: |
          # Style check all formulas
          brew style Formula/
          
          # Basic syntax check for all formulas
          for formula in Formula/*.rb; do
            echo "Checking syntax for $formula"
            ruby -c "$formula"
          done
          echo "✅ All formulas have valid syntax"